project:
  type: website
  render:
    - 404.qmd
    - index.qmd
    - general/scientific-writing.qmd
    - workshops/literature-research.qmd
    - workshops/prompting.qmd
    - workshops/git-github.qmd
    - workshops/large-language-models.qmd
    - workshops/quarto-academic-writing.qmd
    - general/templates.qmd
    - general/literature.qmd
    - general/privacy.qmd
    - general/faq.qmd
  resources:
    - templates/seminar-paper-en.qmd
    - templates/seminar-paper-de.qmd
    - templates/Vorlage.tex
    - templates/references.bib
    - templates/typst-show.typ
    - templates/images/Image.pdf
  post-render:
    - helpers/convert_qmd_to_md.py

website:
  title: "Scientific Research Workshops"
  repo-url: https://github.com/beyondsimulations/Scientific-Research-Workshops
  repo-branch: main
  repo-actions: [edit, source, issue]
  site-url: https://beyondsimulations.github.io/Scientific-Research-Workshops
  bread-crumbs: true
  sidebar:
    style: floating
    logo: https://images.beyondsimulations.com/logo/midjourney-solar-mirror.png
    collapse-level: 1
    search: true
    contents:
      - text: "Welcome"
        href: index.qmd
      - text: "***"
      - text: "Scientific Writing"
        href: general/scientific-writing.qmd
      - text: "Literature"
        href: workshops/literature-research.qmd
      - text: "AI Tools"
        href: workshops/large-language-models.qmd
      - text: "Prompting"
        href: workshops/prompting.qmd
      - text: "Version Control"
        href: workshops/git-github.qmd
      - text: "Quarto"
        href: workshops/quarto-academic-writing.qmd
      - text: "***"
      - text: "Templates"
        href: general/templates.qmd
      - text: "Resources"
        href: general/literature.qmd
      - text: "FAQs"
        href: general/faq.qmd

  page-footer:
    center: "Scientific Research Workshops, Tobias Vlćek</br>CC BY-NC-SA 4.0"
    left:
      - icon: github
        href: https://github.com/beyondsimulations/Scientific-Research-Workshops
      - icon: linkedin
        href: https://linkedin.com/in/tobiasvlcek
      - icon: envelope
        href: mailto:tobias.vlcek@uni-hamburg.de
      - icon: skip-backward
        href: https://tobiasvlcek.com/lectures/
      - icon: shield-check
        href: general/privacy.qmd

format:
  hugo-md: default
  html:
    theme:
      - default
      - styles.scss
      - brand
    toc: true
    highlight-style: github
    callout-appearance: simple
    code-copy: true
    code-link: true
    toc-location: right
    code-overflow: wrap
    include-in-header:
      - general/header.html
    include-after-body:
      text: |
        <script src="https://chat.beyondsimulations.com/widget.js"></script>
        <script>
          ChatWidget.init({
            apiUrl: "https://chat.beyondsimulations.com",
            tenant: "platform",
            agent: "thesis-helper",
          });
        </script>

execute:
  freeze: auto

brand: _brand.yml
